angular.module('app').factory('StatCache', [
  '$cacheFactory'
  ($cacheFactory) ->
    $cacheFactory 'Stat-Cache'
]).factory('StatDauService', [
  '$resource'
  ($resource) ->
    (apikey) ->
      $resource '/ajax/stat/dau/:days'
]).factory('StatCrashRateService', [
  '$resource'
  ($resource) ->
    (apikey) ->
      $resource '/ajax/stat/crash/:days'
]).factory('StatOsVersionService', [
  '$resource'
  ($resource) ->
    (apikey) ->
      $resource '/ajax/stat/os/:days'
]).factory('StatActivityService', [
  '$resource'
  ($resource) ->
    (apikey) ->
      $resource '/ajax/stat/activity/:days'
]).factory('StatDeviceService', [
  '$resource'
  ($resource) ->
    (apikey) ->
      $resource '/ajax/stat/device/:days'
]).factory('StatWorldeService', [
  '$resource'
  ($resource) ->
    (apikey) ->
      $resource '/ajax/stat/world/:days'
]).factory('StatVersionService', [
  '$resource'
  ($resource) ->
    (apikey) ->
      $resource '/ajax/stat/version/:days'
]).factory 'StatClassService', [
  '$resource'
  ($resource) ->
    (apikey) ->
      $resource '/ajax/stat/class/:days'
]

# ---
# generated by js2coffee 2.1.0
