angular.module('app').factory('DashboardErrorPieGraphService', [
  '$resource'
  ($resource) ->
    (apikey) ->
      $resource '/ajax/dashboard/pie'
]).factory('DashboardErrorDailyService', [
  '$resource'
  ($resource) ->
    (apikey) ->
      $resource '/ajax/dashboard/daily'
]).factory 'DashBoardInfoService', [
  '$resource'
  ($resource) ->
    (apikey) ->
      $resource '/ajax/dashboard/info'
]

# ---
# generated by js2coffee 2.1.0
