angular.module('app').controller 'userController', ($scope, UserInfoService) ->
  UserInfoService().get({}).$promise.then ((response) ->
    $scope.user = {}
    $scope.user.name = response.user_name
    $scope.user.profile = response.profile_url
    $scope.user.email = response.user_email
  ), (response) ->
    alert '사용자 정보를 불러올 수 없습니다.'


# ---
# generated by js2coffee 2.1.0
